tablet/urls.py
from django.shortcuts import redirect
from django.urls import include, path

from . import views

app_name = 'tablet'
urlpatterns = [
    path('', lambda r: redirect('tablet:motd'), name="home"),
    path('members/', views.members, name='members'),
    path('motd/', views.motd, name='motd'),
    path('here_today/', views.here_today, name='here_today'),
    path('visitors/', views.visitors, name='visitors'),
    path('search/', views.search, name='search'),
    path('welcome/<username>/', views.welcome, name='welcome'),
    path('profile/<username>/', views.user_profile, name='user_profile'),
    path('post_create/<username>/', views.post_create, name='post_create'),
    path('<username>/signin/', views.signin_user, name='signin_user'),
    path('<username>/guestof/<paid_by>/', views.signin_user_guest, name='signin_guest'),
    path('<username>/documents/', views.document_list, name='document_list'),
    path('<username>/document/<doc_type>/', views.document_view, name='document_view'),
    path('<username>/signature/<doc_type>/', views.signature_capture, name='sig_capture'),
    path('<username>/signature/<doc_type>/<signature_file>', views.signature_render, name='sig_render'),
]

# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

urls.py
import time

from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

import views


admin.autodiscover()

app_name = 'nadine'
urlpatterns = [
    path('', views.index, name='site_index'),
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    path('robots.txt', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    path('cache.manifest', lambda r: HttpResponse(get_manifest(), content_type="text/plain")),

    path('account/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),

    path('staff/', include('staff.urls', namespace='staff')),
    path('member/', include('member.urls', namespace='member')),
    path('tablet/', include('tablet.urls', namespace='tablet')),
    path('doors/', include('doors.keymaster.urls', namespace='doors')),
    path('logs/', include('arpwatch.urls', namespace='arp')),
    path('comlink/', include('comlink.urls', namespace='comlink')),

    path('email/add/', views.email_add, name='email_add'),
    path('email/manage/<email_pk>/<action>/', views.email_manage, name='email_manage'),
    path('email/verify/<email_pk>/', views.email_verify, name='email_verify'),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


def get_manifest():
    return "CACHE MANIFEST\n#Time: %s\nCACHE:\nFALLBACK:\nNETWORK:\n*" % time.time()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

member/views/connect.py
from datetime import date, datetime, timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404, HttpRequest
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from nadine import email
from nadine.models.usage import CoworkingDay
from nadine.models.resource import Room
from nadine.utils.slack_api import SlackAPI

from comlink.forms import MailingListSubscriptionForm
from comlink.models import MailingList, EmailMessage

from member.models import UserNotification
from member.views.core import is_active_member


@login_required
@user_passes_test(is_active_member, login_url='member:not_active')
def connect(request, username):
    target = get_object_or_404(User, username=username)
    user = request.user
    action = request.GET.get('action')
    if action and action == "send_info":
        email.send_contact_request(user, target)
        messages.success(request, "Email Sent")
    context = {'target': target, 'user': user, 'settings': settings}
    return render(request, 'member/connect/connect.html', context)


@login_required
def notifications(request):
    notifications = UserNotification.objects.filter(notify_user=request.user, sent_date__isnull=True)
    return render(request, 'member/connect/notifications.html', {'notifications': notifications})


@login_required
def add_notification(request, username):
    target = get_object_or_404(User, username=username)
    if UserNotification.objects.filter(notify_user=request.user, target_user=target, sent_date__isnull=True).count() == 0:
        UserNotification.objects.create(notify_user=request.user, target_user=target)
    return HttpResponseRedirect(reverse('member:connect:notifications', kwargs={}))


@login_required
def delete_notification(request, username):
    target = get_object_or_404(User, username=username)
    for n in UserNotification.objects.filter(notify_user=request.user, target_user=target):
        n.delete()
    return HttpResponseRedirect(reverse('member:connect:notifications', kwargs={}))


@login_required
def chat(request):
    user = request.user
    return render(request, 'member/connect/chat.html', {'user': user})


@login_required
@user_passes_test(is_active_member, login_url='member:not_active')
def mail(request):
    user = request.user
    if request.method == 'POST':
        sub_form = MailingListSubscriptionForm(request.POST)
        if sub_form.is_valid():
            sub_form.save(user)
            return HttpResponseRedirect(reverse('member:connect:email_lists'))

    mailing_lists = []
    for ml in MailingList.objects.filter(enabled=True).order_by('name'):
        mailing_lists.append({
            'list': ml,
            'is_subscriber': user in ml.subscribers.all(),
            'recents': ml.emailmessage_set.all().order_by('-received')[:20]
        })

    context = {
        'user': user,
        'mailing_lists': mailing_lists,
        'mailing_list_subscription_form': MailingListSubscriptionForm(),
        'settings': settings
    }
    return render(request, 'member/connect/mail.html', context)


@login_required
@user_passes_test(is_active_member, login_url='member:not_active')
def mail_message(request, id):
    message = get_object_or_404(EmailMessage, id=id)
    return render(request, 'member/connect/mail_message.html', {'message': message, 'settings': settings})


@login_required
def slack_redirect(request):
    return HttpResponseRedirect(reverse('member:connect:slack', kwargs={'username': request.user.username}))


@login_required
def slack(request, username):
    user = get_object_or_404(User, username=username)
    if not user == request.user:
        if not request.user.is_staff:
            return HttpResponseRedirect(reverse('member:profile:view', kwargs={'username': request.user.username}))

    if request.method == 'POST':
        try:
            slack_api = SlackAPI()
            slack_api.invite_user(user)
            messages.add_message(request, messages.INFO, "Slack Invitation Sent.  Check your email for further instructions.")
        except Exception as e:
            messages.add_message(request, messages.ERROR, "Failed to send invitation: %s" % e)

    context = {'user': user,
               'team_url': settings.SLACK_TEAM_URL,
               'settings': settings
               }
    return render(request, 'member/connect/slack.html', context)


@csrf_exempt
def slack_bots(request):
    # Stupid chat bot
    try:
        text = request.POST.get("text")[7:]
        SlackAPI().post_message(text)
    except Exception as e:
        return JsonResponse({'text': str(e)})
    return JsonResponse({})


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

member/views/json.py
from datetime import date, datetime, timedelta

from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404, HttpRequest, JsonResponse

from nadine.models.profile import UserProfile
from nadine.models.organization import Organization

from member.views.core import is_active_member

######################################################################
# Helper Functions
######################################################################


def query_to_item_list(query):
    items = []
    for i in query.order_by('name'):
        items.append({'id': i.id, 'value': i.name, })
    return items


def filter_query(query, term):
    if len(term) >= 3:
        query = query.filter(name__icontains=term)
    elif len(term) > 0:
        query = query.filter(name__istartswith=term)
    return query


######################################################################
# Views
######################################################################

# TODO - These should be class views. --JLS

@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def user_tags(request):
    term = request.GET.get('term', '').strip()
    query = UserProfile.tags.all()
    query = filter_query(query, term)
    items = query_to_item_list(query)
    return JsonResponse(items, safe=False)


@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def org_tags(request):
    term = request.GET.get('term', '').strip()
    query = Organization.tags.all()
    query = filter_query(query, term)
    items = query_to_item_list(query)
    return JsonResponse(items, safe=False)


@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def org_search(request):
    term = request.GET.get('term', '').strip()
    query = Organization.objects.all()
    query = filter_query(query, term)
    items = query_to_item_list(query)
    return JsonResponse(items, safe=False)


@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def user_search(request):
    term = request.GET.get('term', '').strip()
    query = User.objects.all()
    if len(term) >= 3:
        if ' ' in term:
            terms = term.split(' ')
            first = Q(first_name__icontains=terms[0])
            last = Q(last_name__icontains=terms[1])
            query = query.filter(first & last)
        else:
            first = Q(first_name__icontains=term)
            last = Q(last_name__icontains=term)
            query = query.filter(first | last)
    elif len(term) > 0:
        query = query.filter(first_name__istartswith=term)
    items = []
    for i in query.order_by('first_name'):
        items.append({'id': i.id,
                      'label': i.get_full_name(),
                      'value': i.username,
                      })
    return JsonResponse(items, safe=False)


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/member/views/json.py
from datetime import date, datetime, timedelta

from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404, HttpRequest, JsonResponse

from nadine.models.profile import UserProfile
from nadine.models.organization import Organization

from member.views.core import is_active_member

######################################################################
# Helper Functions
######################################################################


def query_to_item_list(query):
    items = []
    for i in query.order_by('name'):
        items.append({'id': i.id, 'value': i.name, })
    return items


def filter_query(query, term):
    if len(term) >= 3:
        query = query.filter(name__icontains=term)
    elif len(term) > 0:
        query = query.filter(name__istartswith=term)
    return query


######################################################################
# Views
######################################################################

# TODO - These should be class views. --JLS

@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def user_tags(request):
    term = request.GET.get('term', '').strip()
    query = UserProfile.tags.all()
    query = filter_query(query, term)
    items = query_to_item_list(query)
    return JsonResponse(items, safe=False)


@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def org_tags(request):
    term = request.GET.get('term', '').strip()
    query = Organization.tags.all()
    query = filter_query(query, term)
    items = query_to_item_list(query)
    return JsonResponse(items, safe=False)


@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def org_search(request):
    term = request.GET.get('term', '').strip()
    query = Organization.objects.all()
    query = filter_query(query, term)
    items = query_to_item_list(query)
    return JsonResponse(items, safe=False)


@login_required
@user_passes_test(is_active_member, login_url='/404.html')
def user_search(request):
    term = request.GET.get('term', '').strip()
    query = User.objects.all()
    if len(term) >= 3:
        if ' ' in term:
            terms = term.split(' ')
            first = Q(first_name__icontains=terms[0])
            last = Q(last_name__icontains=terms[1])
            query = query.filter(first & last)
        else:
            first = Q(first_name__icontains=term)
            last = Q(last_name__icontains=term)
            query = query.filter(first | last)
    elif len(term) > 0:
        query = query.filter(first_name__istartswith=term)
    items = []
    for i in query.order_by('first_name'):
        items.append({'id': i.id,
                      'label': i.get_full_name(),
                      'value': i.username,
                      })
    return JsonResponse(items, safe=False)


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/member/templates/member/base.html
{% load integrated_systems %}
{% load settings_value %}
{% load social_links %}
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="DC.title" content="{{ site.name }}" />
  <title>{% block title %}{% block sub-title %}{% endblock %}{{ site.name }}{% endblock %}</title>
  <link rel="shortcut icon" href="{%  static 'img/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"  />
  <link rel="stylesheet" href="{% static 'css/jquery-custom.css' %}">
  <link rel='stylesheet' href="{% static 'js/fullcalendar/fullcalendar.css' %}" />
  <link rel = 'stylesheet' href="{% static 'css/jquery.timepicker.min.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Oswald|Roboto+Condensed" rel="stylesheet">
  <link  href="{% static 'css/cropper.min.css' %}" rel="stylesheet">

  <!--[if IE]>
  <script src="{{ STATIC_URL }}js/html5.js"></script>
  <![endif]-->
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui-1.12.1.min.js' %}"></script>
  <script src="{% static 'js/fullcalendar/lib/moment.min.js' %}"></script>
  <script src="{% static 'js/fullcalendar/fullcalendar.min.js' %}"></script>
  <script src="{% static 'js/fullcalendar/gcal.js' %}"></script>
  <script src="{% static 'js/timepicker/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/jquery.formset.js' %}"></script>
  <script src="{% static 'js/cropper.min.js' %}"></script>

  {% block scripts %}
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
    <!-- Compiled and minified JavaScript -->
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <!-- Fonts are fun -->
    <link href="{% static 'fonts/roboto/Roboto-Regular.eot' %}" rel="stylesheet">
  {% endblock %}

  <link rel="stylesheet" type="text/css" href= "{% static 'css/member.css'%}" />

  {% block pagestyle %}{% endblock %}

  {% if not request.user.is_staff %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', '{% settings_value "GOOGLE_ANALYTICS_ID" %}', 'auto');
      ga('send', 'pageview');
    </script>
  {% endif %}

  {%block sub-head %}{% endblock %}

  <style>
    {% block style %}{% endblock %}
  </style>
</head>

<body>
  {% load_integrations as integrations %}
  {% block body %}
  {% block top_div %}{% endblock %}

  <!-- Page  -->
  <div id="header_container">
      <div id="header">
        {% block top_nav %}
        <nav class='row' id='main-nav'>
          <div class='nav-wrapper'>
            <div id='logo'>
              <a href="{% url 'member:home' %}" class='brand-logo' id="home">
              <img class='sec-logo' src="{% static 'img/logo-line.png' %}"/>
              </a>
            </div>
            <a href='#' data-activates="mobile" class="button-collapse"><img class='menu-img' src="{% static 'img/hamburger.png' %}"/></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'member:help' %}">Help</a></li>
        {% endblock %}
          {% if request.user.profile.is_active %}
            <li>
              <a class='dropdown-button' data-hover="true" data-beloworigin="true" data-activates='dropdown1' href="{% url 'member:members' %}">Members</a>
              <ul id='dropdown1' class='dropdown-content'>
                <li><a href="{% url 'member:members' %}">Active Members</a></li>
                <li><a href="{% url 'member:tag:cloud' 'members' %}">Tags</a></li>
              </ul>
            </li>
            <li>
              <a class='dropdown-button' data-hover="true" data-beloworigin="true" data-activates='dropdown2' href="{% url 'member:org:list' %}">Organizations</a>
              <ul id='dropdown2' class='dropdown-content'>
                <li><a href="{% url 'member:org:list' %}">Active Organizations</a></li>
              <li><a href="{% url 'member:tag:cloud' 'organizations' %}">Tags</a></li>
              </ul>
            </li>
            <li><a href="{% url 'member:event:calendar' %}">Events</a></li>
            <li><a href="{% url 'member:connect:email_lists' %}">Mailing Lists</a></li>
            {% if integrations.slack %}
              <li><a class='slack-a' href="{% url 'member:connect:slack' user.username %}">Slack</a></li>
            {% endif %}
            <li><a href="{% url 'member:profile:redirect' %}">Profile</a></li>
            <li>
              <a class='logout-a dropdown-button' data-hover="true" data-beloworigin="true" data-activates='dropdown3' href="{% url 'logout' %}">Logout</a>
              <ul id='dropdown3' class='dropdown-content'>
                {% if request.user.is_staff %}
                  <li><a href="{% url 'staff:home' %}">Staff</a></li>
                  <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
              </ul>
            </li>
          {% else %}
            <li><a href="{% url 'member:not_active' %}">Members</a></li>
            <li><a href="{% url 'member:not_active' %}">Organizations</a></li>
            <li><a href="{% url 'member:not_active' %}">Events</a></li>
            <li><a href="{% url 'member:not_active' %}">Mailing Lists</a></li>
            {% if integrations.slack %}
              <li><a href="{% url 'member:not_active' %}">Slack</a></li>
            {% endif %}
            <li><a href="{% url 'member:profile:redirect' %}">Profile</a></li>
            <li>
              <a class='logout-a dropdown-button' data-hover="true" data-beloworigin="true" data-activates='dropdown3' href="{% url 'logout' %}">Logout</a>
              <ul id='dropdown3' class='dropdown-content'>
                {% if request.user.is_staff %}
                  <li><a href="{% url 'staff:home' %}">Staff</a></li>
                  <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
              </ul>
            </li>
          {% endif %}
          </ul>

          {% block side-nav %}
            <ul class="side-nav" id="mobile">
              {% if request.user.profile.is_active %}
                <li><a href="{% url 'member:help' %}">Help</a></li>
                <li><a href="{% url 'member:members' %}">Members</a></li>
                <li><a href="{% url 'member:org:list' %}">Organizations</a></li>
                <li><a href="{% url 'member:event:calendar' %}">Events</a></li>
                <li><a href="{% url 'member:connect:email_lists' %}">Mailing Lists</a></li>
                {% if integrations.slack %}
                  <li><a class='slack-a' href="{% url 'member:connect:slack' user.username %}">Slack</a></li>
                {% endif %}
                <li><a href="{% url 'member:profile:redirect' %}">Profile</a></li>
                <li><a class='logout-a' href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'member:not_active' %}">Help</a></li>
                <li><a href="{% url 'member:not_active' %}">Members</a></li>
                <li><a href="{% url 'member:not_active' %}">Organizations</a></li>
                <li><a href="{% url 'member:not_active' %}">Events</a></li>
                <li><a href="{% url 'member:not_active' %}">Tags</a></li>
                <li><a href="{% url 'member:not_active' %}">Mailing Lists</a></li>
                {% if integrations.slack %}
                  <li><a href="{% url 'member:not_active' %}">Slack</a></li>
                {% endif %}
                <li><a href="{% url 'member:profile:redirect' %}">Profile</a></li>
                <li><a class='logout-a' href="{% url 'logout' %}">Logout</a></li>
              {% endif %}
            </ul>
          {% endblock %}
          </div>
        </nav>
      {% block lower_nav %}{% endblock %}
    </div>
  </div>

  {% block main_body %}
    <div>
      <div class='row main'>
        <div class="lightbg col s10 offset-s1">
          <div id="content">
          {% block content %}{% endblock %}
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

  <!-- Footer -->
  {% block footer %}
    {% block footer-class %}
      <footer class="page-footer main-footer" id="footer">
    {% endblock %}
    <div class="footer-copyright setwidth container">
      {% block upperfooter %}
        <div id="copyright">
          © 2020 |  Office Nomads | <a id='nadine-link' href="https://nadineproject.org/" target="_new">The Nadine Project</a>
        </div>
      {% endblock %}
      {% block lowerfooter %}
        {% load_social_urls as social %}
        <div class='grey-text text-lighten-4 right' id="social">
          {% if social.facebook %}
            <a id="fb" target="_blank" href="{{ social.facebook }}">fb</a>
          {% endif %}
          {% if social.twitter %}
            <a id="tw" target="_blank" href="{{ social.twitter }}">tw</a>
          {% endif %}
          {% if social.yelp %}
            <a id="ye" target="_blank" href="{{ social.yelp }}">ye</a>
          {% endif %}
          {% if social.instagram %}
            <a id='inst' target='_blank' href="{{ social.instagram }}">inst</a>
          {% endif %}
        </div>
      {% endblock %}
      </div>
    </div>
    </footer>
    {% endblock %}
    </div>
    {% block bottom_div %} {% endblock %}
  {% endblock %}

  {% block extrajs %}
    <script>
      $(document).ready(function(){
        $('.button-collapse').sideNav();
        $('.dropdown-button').dropdown();

        if($('.main').height() < 900) {
          $('footer').attr('class', 'sticky-footer');
        } else {
          if($('footer').hasClass('sticky-footer')) {
            $('footer').attr('page-footer main-footer');
          }
        }
      });
    </script>
  {% endblock %}
</body>
</html>

nadine-2.2.3/member/templates/member/new_billing.html
{% extends "member/base.html" %}

{% block style %}
{% endblock %}

{% block sub-title %}New Billing | {% endblock %}

{% block content %}
<h2>New Billing Profile - {{ username }}</h2>

{% if error %}
	<div style="text-align:center; font-size:150%; color:red">{{ error }}</div>
{% else %}
	<p style="padding-top:1em;">
		Thank you very much!
	</p>
	<p>Your new billing profile has been approved. If you have any billing related questions
		please stop by the front desk or send an email to <a href="mailto:billing@officenomads.com">billing@officenomads.com</a>.
		Also, please take a moment to <a href="{% url 'member:help_topic' 'billing' %}">review how we handle billing.</a>
	</p>
	<p>- <a href="mailto:staff@officenomads.com">The Office Nomads Team</a></p>
{% endif %}

{% endblock %}

nadine-2.2.3/member/templates/member/spinner.html
<div class="preloader-wrapper big active">
  <div class="spinner-layer spinner-blue-only">
    <div class="circle-clipper left">
      <div class="circle"></div>
    </div><div class="gap-patch">
      <div class="circle"></div>
    </div><div class="circle-clipper right">
      <div class="circle"></div>
    </div>
  </div>
</div>

nadine-2.2.3/member/templates/member/websites.html
<div class='profile-links'>
  {% for url in websites.all %}
    <li class='bold-blue url-links'>
      <a target="_self" href="{{ url }}"><img class='tooltipped' data-position='bottom' data-tooltip='{{ url.url_type | title }}' id='{{ url.url_type | title}}' /></a>
    </li>
  {% endfor %}
</div>