arpwatch/urls.py
from django.urls import path

from arpwatch import views


app_name = 'arpwatch'
urlpatterns = [
   path('', views.home, name='home'),
   path('import/', views.import_files, name='import'),
   path('devices/', views.device_list, name='devices'),
   path('device/(<int:device_id>)/', views.device, name='device'),
   path('device/', views.device_logs_today, name='devices_today'),
   path('device/<int:year>/<int:month>/<day>/', views.device_logs_by_day, name='device_logs'),
   path('user/', views.logins_today, name='user'),
   path('user/<int:year>/<int:month>/<int:day>/', views.logins_by_day, name='user_logs'),
]


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/arpwatch/urls.py
from django.urls import path

from arpwatch import views


app_name = 'arpwatch'
urlpatterns = [
   path('', views.home, name='home'),
   path('import/', views.import_files, name='import'),
   path('devices/', views.device_list, name='devices'),
   path('device/(<int:device_id>)/', views.device, name='device'),
   path('device/', views.device_logs_today, name='devices_today'),
   path('device/<int:year>/<int:month>/<day>/', views.device_logs_by_day, name='device_logs'),
   path('user/', views.logins_today, name='user'),
   path('user/<int:year>/<int:month>/<int:day>/', views.logins_by_day, name='user_logs'),
]


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

urls.py
import time

from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

import views


admin.autodiscover()

app_name = 'nadine'
urlpatterns = [
    path('', views.index, name='site_index'),
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    path('robots.txt', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    path('cache.manifest', lambda r: HttpResponse(get_manifest(), content_type="text/plain")),

    path('account/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),

    path('staff/', include('staff.urls', namespace='staff')),
    path('member/', include('member.urls', namespace='member')),
    path('tablet/', include('tablet.urls', namespace='tablet')),
    path('doors/', include('doors.keymaster.urls', namespace='doors')),
    path('logs/', include('arpwatch.urls', namespace='arp')),
    path('comlink/', include('comlink.urls', namespace='comlink')),

    path('email/add/', views.email_add, name='email_add'),
    path('email/manage/<email_pk>/<action>/', views.email_manage, name='email_manage'),
    path('email/verify/<email_pk>/', views.email_verify, name='email_verify'),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


def get_manifest():
    return "CACHE MANIFEST\n#Time: %s\nCACHE:\nFALLBACK:\nNETWORK:\n*" % time.time()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

arpwatch/forms.py
from django import forms


class UploadFileForm(forms.Form):
    #title = forms.CharField(max_length=50)
    file = forms.FileField()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/arpwatch/forms.py
from django import forms


class UploadFileForm(forms.Form):
    #title = forms.CharField(max_length=50)
    file = forms.FileField()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

arpwatch/views.py
from datetime import datetime, timedelta, date

from django.contrib import auth
from django.conf import settings
from django.template import RequestContext
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseServerError, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.timezone import localtime, now, make_aware, get_current_timezone

from arpwatch.forms import *
from arpwatch.models import *
from arpwatch import arp


@staff_member_required
def home(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            # Check the upload logs to make sure we haven't already loaded this file
            if (UploadLog.objects.filter(file_name=file.name).count() > 0):
                raise Exception('File Already Loaded')
            if request.user.is_authenticated():
                UploadLog.objects.create(user=request.user, file_name=file.name, file_size=file.size)
            else:
                UploadLog.objects.create(file_name=file.name, file_size=file.size)
            arp.import_file(file)
            # return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'arpwatch/home.html', {'form': form})


def import_files(request):
    page_message = "success"
    try:
        arp.import_all()
    except RuntimeError as err:
        page_message = err

    return render(request, 'arpwatch/import.html', {'page_message': page_message})


@staff_member_required
def device_list(request):
    devices = UserDevice.objects.filter(ignore=False)
    return render(request, 'arpwatch/device_list.html', {'devices': devices})


@staff_member_required
def device(request, device_id):
    device = UserDevice.objects.get(pk=device_id)
    logs = ArpLog.objects.for_device(device_id)
    return render(request, 'arpwatch/device_view.html', {'device': device, 'logs': logs})


@staff_member_required
def device_logs_today(request):
    today = localtime(now())
    return device_logs_by_day(request, str(today.year), str(today.month), str(today.day))


@staff_member_required
def device_logs_by_day(request, year, month, day):
    log_date = date(year=int(year), month=int(month), day=int(day))
    start = datetime(year=int(year), month=int(month), day=int(day), hour=0, minute=0, second=0, microsecond=0)
    start = make_aware(start, get_current_timezone())
    end = start + timedelta(days=1)
    device_logs = ArpLog.objects.for_range(start, end)
    context = {'device_logs': device_logs, 'day': log_date,
        'next_day': log_date + timedelta(days=1),
        'previous_day': log_date - timedelta(days=1)}
    return render(request, 'arpwatch/device_logs.html', context)


@staff_member_required
def logins_today(request):
    today = localtime(now())
    return logins_by_day(request, str(today.year), str(today.month), str(today.day))


def logins_by_day(request, year, month, day):
    log_date = date(year=int(year), month=int(month), day=int(day))
    start = datetime(year=int(year), month=int(month), day=int(day), hour=0, minute=0, second=0, microsecond=0)
    start = make_aware(start, get_current_timezone())
    end = start + timedelta(days=1)
    logs = UserRemoteAddr.objects.filter(logintime__gt=start, logintime__lt=end)
    context = {'logs': logs, 'day': log_date,
        'next_day': log_date + timedelta(days=1),
        'previous_day': log_date - timedelta(days=1)}
    return render(request, 'arpwatch/user_logins.html', context)


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/arpwatch/views.py
from datetime import datetime, timedelta, date

from django.contrib import auth
from django.conf import settings
from django.template import RequestContext
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseServerError, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.timezone import localtime, now, make_aware, get_current_timezone

from arpwatch.forms import *
from arpwatch.models import *
from arpwatch import arp


@staff_member_required
def home(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            # Check the upload logs to make sure we haven't already loaded this file
            if (UploadLog.objects.filter(file_name=file.name).count() > 0):
                raise Exception('File Already Loaded')
            if request.user.is_authenticated():
                UploadLog.objects.create(user=request.user, file_name=file.name, file_size=file.size)
            else:
                UploadLog.objects.create(file_name=file.name, file_size=file.size)
            arp.import_file(file)
            # return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'arpwatch/home.html', {'form': form})


def import_files(request):
    page_message = "success"
    try:
        arp.import_all()
    except RuntimeError as err:
        page_message = err

    return render(request, 'arpwatch/import.html', {'page_message': page_message})


@staff_member_required
def device_list(request):
    devices = UserDevice.objects.filter(ignore=False)
    return render(request, 'arpwatch/device_list.html', {'devices': devices})


@staff_member_required
def device(request, device_id):
    device = UserDevice.objects.get(pk=device_id)
    logs = ArpLog.objects.for_device(device_id)
    return render(request, 'arpwatch/device_view.html', {'device': device, 'logs': logs})


@staff_member_required
def device_logs_today(request):
    today = localtime(now())
    return device_logs_by_day(request, str(today.year), str(today.month), str(today.day))


@staff_member_required
def device_logs_by_day(request, year, month, day):
    log_date = date(year=int(year), month=int(month), day=int(day))
    start = datetime(year=int(year), month=int(month), day=int(day), hour=0, minute=0, second=0, microsecond=0)
    start = make_aware(start, get_current_timezone())
    end = start + timedelta(days=1)
    device_logs = ArpLog.objects.for_range(start, end)
    context = {'device_logs': device_logs, 'day': log_date,
        'next_day': log_date + timedelta(days=1),
        'previous_day': log_date - timedelta(days=1)}
    return render(request, 'arpwatch/device_logs.html', context)


@staff_member_required
def logins_today(request):
    today = localtime(now())
    return logins_by_day(request, str(today.year), str(today.month), str(today.day))


def logins_by_day(request, year, month, day):
    log_date = date(year=int(year), month=int(month), day=int(day))
    start = datetime(year=int(year), month=int(month), day=int(day), hour=0, minute=0, second=0, microsecond=0)
    start = make_aware(start, get_current_timezone())
    end = start + timedelta(days=1)
    logs = UserRemoteAddr.objects.filter(logintime__gt=start, logintime__lt=end)
    context = {'logs': logs, 'day': log_date,
        'next_day': log_date + timedelta(days=1),
        'previous_day': log_date - timedelta(days=1)}
    return render(request, 'arpwatch/user_logins.html', context)


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/arpwatch/templates/arpwatch/base.html
{% extends "staff/base.html" %}
{% load static %}

{% block sub-title %}Logs{% endblock %}

{% block pagestyle %}
	<link rel='stylesheet' href="{% static 'staff/css/arpwatch.css' %}" />
{% endblock %}

{% block submenu %}
	<a href="{% url 'arp:devices_today' %}">Device Logs</a> |
	<a href="{% url 'arp:user' %}">User Logins</a>
{% endblock %}

{% block content %}
{% endblock %}

{% block navcss %}
<style>
	#logs-tab {
		color: RGBA(90, 122, 189, 1.00) !important;
	}
</style>
{% endblock %}

nadine-2.2.3/arpwatch/templates/arpwatch/device_list.html
<h3>Devices</h3>

<ul>
	{% for device in devices %}
		<li><a href="{% url 'arpwatch_device' device.id %}">{{ device }}</a></li>
	{% endfor %}
</ul>

nadine-2.2.3/arpwatch/templates/arpwatch/device_logs.html
{% extends "arpwatch/base.html" %}

{% block content %}

<div>
	<div style="size:large; float:right;"><strong>{{ device_logs|length }} Logs</strong></div>
	<h4>Device Logs - {{ day|date:"M d, Y" }}</h4>
</div>

<h5 align="center">
	<a href="{% url 'arp:device_logs' previous_day.year previous_day.month previous_day.day %}">&laquo; Prev</a>
	[ <a href="{% url 'arp:devices_today' %}">Today</a> ]
	<a href="{% url 'arp:device_logs' next_day.year next_day.month next_day.day %}">Next &raquo;</a>
</h5>

<table border=1>
	<tr>
		<th>Device</th>
		<th>Start</th>
		<th>End</th>
		<th>Duration</th>
		<th></th>
	</tr>
	{% for l in device_logs %}
		<tr>
			<td><a href="{% url 'arp:device' l.device.id %}">{{ l.device }}</a></td>
			<td>{{ l.start|date:"h:i a" }}</td>
			<td>{{ l.end|date:"h:i a" }}</td>
			<td>{{ l.diff }}</td>
			<td></td>
		</tr>
	{% endfor %}
</table>

{% endblock %}

nadine-2.2.3/arpwatch/templates/arpwatch/device_view.html
{% extends "arpwatch/base.html" %}

{% block content %}

<h3>Device Info</h3>
<table>
	<tr>
		<th>User</th>
		<td>{{ device.user }}</td>
	</tr>
	<tr>
		<th>Device Name</th>
		<td>{{ device.device_name }}</td>
	</tr>
	<tr>
		<th>MAC Address</th>
		<td>{{ device.mac_address }}</td>
	</tr>
</table>

<h3>Logs</h3>
<table>
	<tr>
		<th>Date</th>
		<th>IP Address</th>
		<th/>
	</tr>
	{% for log in logs %}
		<tr>
			<td><a href="{% url 'arp:device_logs' log.day|date:'Y' log.day|date:'m' log.day|date:'d' %}">{{ log.day|date:"M d, Y" }}</a></td>
			<td>{{ log.ip }}</td>
			<td/>
		</tr>
	{% endfor %}
</table>

{% endblock %}

nadine-2.2.3/arpwatch/templates/arpwatch/home.html
<h2>ArpWatch: Good times!</h2>

<h3>Things to do</h3>
<ul>
	<li><a href="{% url 'arp:devices' %}">View All Devices</a></li>
	<li><a href="{% url 'arp:devices_today' %}">View Logs By Day</a></li>
</ul>

<h3>Upload a File!</h3>
<form action="." method="POST" enctype="multipart/form-data">
	{% for field in form %}{{ field }}{% endfor %}<br/>
	<input type="submit" value="upload" />
	{% csrf_token %}
</form>

nadine-2.2.3/arpwatch/templates/arpwatch/import.html
{{page_message}}

nadine-2.2.3/arpwatch/templates/arpwatch/nav.html
<li>
  <a href="{% url 'arp:devices_today' %}">Device Logs</a>
</li>
<li>
  <a href="{% url 'arp:user' %}">User Logins</a>
</li>

nadine-2.2.3/arpwatch/templates/arpwatch/user_logins.html
{% extends "arpwatch/base.html" %}

{% block content %}
<div>
	<div id='logs-length'><strong>{{ logs|length }} Logins</strong></div>
	<h4>User Logins - {{ day|date:"M d, Y" }}</h4>
</div>

<h5 align="center">
	<a href="{% url 'arp:user_logs' previous_day.year previous_day.month previous_day.day %}">&laquo; Prev</a>
	[ <a href="{% url 'arp:user' %}">Today</a> ]
	<a href="{% url 'arp:user_logs' next_day.year next_day.month next_day.day %}">Next &raquo;</a>
</h5>

<table border=1>
	<tr>
		<th>Time</th>
		<th>User</th>
		<th>IP Address</th>
		<th></th>
	</tr>
	{% for l in logs %}
		<tr>
			<td>{{ l.logintime|date:"h:i a" }}</td>
			<td>{{ l.user.profile }}</td>
			<td>{{ l.ip_address }}</td>
			<td></td>
		</tr>
	{% endfor %}
</table>

{% endblock %}