urls.py
import time

from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

import views


admin.autodiscover()

app_name = 'nadine'
urlpatterns = [
    path('', views.index, name='site_index'),
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    path('robots.txt', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    path('cache.manifest', lambda r: HttpResponse(get_manifest(), content_type="text/plain")),

    path('account/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),

    path('staff/', include('staff.urls', namespace='staff')),
    path('member/', include('member.urls', namespace='member')),
    path('tablet/', include('tablet.urls', namespace='tablet')),
    path('doors/', include('doors.keymaster.urls', namespace='doors')),
    path('logs/', include('arpwatch.urls', namespace='arp')),
    path('comlink/', include('comlink.urls', namespace='comlink')),

    path('email/add/', views.email_add, name='email_add'),
    path('email/manage/<email_pk>/<action>/', views.email_manage, name='email_manage'),
    path('email/verify/<email_pk>/', views.email_verify, name='email_verify'),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


def get_manifest():
    return "CACHE MANIFEST\n#Time: %s\nCACHE:\nFALLBACK:\nNETWORK:\n*" % time.time()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

member/models.py
from django.db import models
from django.db.models import Q
from django.contrib import admin
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.conf import settings


class MOTDManager(models.Manager):

    def for_date(self, day=None):
        if not day:
            day = timezone.now()
        return MOTD.objects.filter(start_ts__lte=day, end_ts__gte=day).first()

    def for_today(self):
        today = timezone.now()
        motd = self.for_date(today)
        if not motd:
            message = settings.MOTD
            if not message:
                message = "Welcome!"
            delay = settings.MOTD_TIMEOUT
            if not delay:
                delay=10000
            motd = MOTD(start_ts=today, end_ts=today, message=message, delay_ms=delay)
        return motd


class MOTD(models.Model):
    objects = MOTDManager()

    start_ts = models.DateTimeField(null=False, blank=False)
    end_ts = models.DateTimeField(null=False, blank=False)
    message = models.TextField(null=False, blank=False)
    delay_ms = models.SmallIntegerField(null=False, blank=False, default=5000)

    def __str__(self):
        return self.message


class HelpText(models.Model):
    title = models.CharField(max_length=128)
    template = models.TextField(blank=True, null=True)
    slug = models.CharField(max_length=16, unique=True)
    order = models.SmallIntegerField()

    def __str__(self): return self.title


class UserNotification(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    notify_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="notify", blank=False, on_delete=models.CASCADE)
    target_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="target", blank=False, on_delete=models.CASCADE)
    sent_date = models.DateTimeField(blank=True, null=True, default=None)


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine/forms.py
import logging
import datetime
import base64
import uuid
import os
from datetime import datetime, timedelta

from django import forms
from django.core.files.base import ContentFile
from django.forms import modelformset_factory
from django.forms.formsets import BaseFormSet
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.base import ContentFile
from django.utils.timezone import localtime, now
from django.shortcuts import get_object_or_404

from localflavor.us.us_states import US_STATES
from localflavor.ca.ca_provinces import PROVINCE_CHOICES

from comlink import mailgun

from nadine.models.core import HowHeard, Industry, Neighborhood, URLType, GENDER_CHOICES
from nadine.models.profile import UserProfile, MemberNote, user_photo_path
from nadine.models.membership import Membership, MembershipPackage, ResourceSubscription, IndividualMembership, SubscriptionDefault
from nadine.models.usage import PAYMENT_CHOICES, CoworkingDay
from nadine.models.resource import Room, Resource
from nadine.models.organization import Organization, OrganizationMember
from nadine.models.billing import UserBill, Payment, PaymentMethod
from nadine.utils.payment_api import PaymentAPI
from member.models import HelpText, MOTD

logger = logging.getLogger(__name__)


class DateRangeForm(forms.Form):
    START_DATE_PARAM = 'start'
    END_DATE_PARAM = 'end'

    start = forms.DateField()
    end = forms.DateField()

    @staticmethod
    def from_request(request, days=31):
        # Pull the start and end parameters
        start_param = DateRangeForm.START_DATE_PARAM
        end_param = DateRangeForm.END_DATE_PARAM
        # Get our start date
        start_str = request.POST.get(start_param, None)
        if not start_str:
            start_str = request.GET.get(start_param, None)
        if not start_str:
            start_date = localtime(now()).date() - timedelta(days=days)
            start_str = start_date.isoformat()
        # Get our end date
        end_str = request.POST.get(end_param, None)
        if not end_str:
            end_str = request.GET.get(end_param, None)
        if not end_str:
            tomorrow = localtime(now()) + timedelta(days=1)
            end_str = tomorrow.date().isoformat()
        return DateRangeForm({start_param: start_str, end_param: end_str})

    def get_dates(self):
        if not self.is_valid():
            return (None, None)
        return (self.cleaned_data['start'], self.cleaned_data['end'])


class OrganizationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            self.instance = kwargs['instance']
            del kwargs['instance']
        super(OrganizationForm, self).__init__(*args, **kwargs)
        if hasattr(self, 'instance'):
            self.initial['org_id'] = self.instance.id
            self.initial['name'] = self.instance.name
            self.initial['blurb'] = self.instance.blurb
            self.initial['bio'] = self.instance.bio
            self.initial['photo'] = self.instance.photo
            self.initial['public'] = self.instance.public
            #self.initial['locked'] = self.instance.locked

    org_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    name = forms.CharField(min_length=1, max_length=128, label="Organization Name", required=True, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    blurb = forms.CharField(widget=forms.Textarea, max_length=112, required=False)
    bio = forms.CharField(widget=forms.Textarea, max_length=512, required=False)
    photo = forms.FileField(required=False)
    public = forms.BooleanField(required=False)
    #locked = forms.BooleanField(required=False)

    def save(self):
        org_id = self.cleaned_data['org_id']
        org = Organization.objects.get(id=org_id)
        org.name = self.cleaned_data['name']
        org.blurb = self.cleaned_data['blurb']
        org.bio = self.cleaned_data['bio']
        if self.cleaned_data['photo']:
            # Delete the old one before we save the new one
            org.photo.delete()
            org.photo = self.cleaned_data['photo']
        if 'public' in self.cleaned_data:
            org.public = self.cleaned_data['public']
        if 'locked' in self.cleaned_data:
            org.locked = self.cleaned_data['locked']
        org.save()


class OrganizationSearchForm(forms.Form):
    terms = forms.CharField(max_length=100)


class OrganizationMemberForm(forms.Form):
    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            self.instance = kwargs['instance']
            del kwargs['instance']
        super(OrganizationMemberForm, self).__init__(*args, **kwargs)
        if hasattr(self, 'instance'):
            self.initial['member_id'] = self.instance.id
            self.initial['org_id'] = self.instance.organization.id
            self.initial['username'] = self.instance.user.username
            self.initial['title'] = self.instance.title
            self.initial['start_date'] = self.instance.start_date
            self.initial['end_date'] = self.instance.end_date
            self.initial['admin'] = self.instance.admin

    org_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    member_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    username = forms.CharField(required=False, widget=forms.HiddenInput)
    title = forms.CharField(max_length=128, required=False, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder':'e.g. 12/28/16', 'class':'datepicker'}, format='%m/%d/%Y'), required=True)
    end_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder':'e.g. 12/28/16', 'class':'datepicker'}, format='%m/%d/%Y'), required=False)
    admin = forms.BooleanField(required=False)

    def is_valid(self):
        # run the parent validation first
        super_valid = super(OrganizationMemberForm, self).is_valid()
        has_member_id = 'member_id' in self.cleaned_data and self.cleaned_data['member_id']
        has_username = 'username' in self.cleaned_data and self.cleaned_data['username']
        if not (has_member_id or has_username):
            self.add_error('username', 'No user data provided')
        return super_valid and (has_member_id or has_username)

    def clean_member(self):
        self.member = None
        self.organization = Organization.objects.get(id=self.cleaned_data['org_id'])

        # Populate our member from either member_id (edit) or username (add)
        member_id = self.cleaned_data['member_id']
        username=self.cleaned_data['username']
        if member_id:
            self.member = OrganizationMember.objects.get(id=member_id)
        elif username:
            user = User.objects.get(username=username)
            self.member = OrganizationMember(organization=self.organization, user=user)
        else:
            raise Exception("Form must contain member_id or username!")

        return self.member

    def save(self):
        if not self.is_valid():
            raise Exception('The form must be valid in order to save')
        member = self.clean_member()
        member.title = self.cleaned_data['title']
        member.start_date = self.cleaned_data['start_date']
        member.end_date = self.cleaned_data['end_date']
        if 'admin' in self.cleaned_data:
            member.admin = self.cleaned_data['admin']
        member.save()


class PaymentForm(forms.Form):
    bill_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    username = forms.CharField(required=True, widget=forms.HiddenInput)
    # created_by = forms.CharField(required=False, widget=forms.HiddenInput)
    payment_date = forms.DateField(required=True, widget=forms.DateInput(attrs={'placeholder':'e.g. 12/28/16', 'class':'datepicker'}, format='%m/%d/%Y'))
    method = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'browser-default'}), label="Payment method", queryset=PaymentMethod.objects.all(), required=False)
    note = forms.CharField(max_length=256, required=False)
    amount = forms.DecimalField(min_value=0, max_value=10000, required=True, max_digits=7, decimal_places=2)

    def save(self, created_by=None):
        bill = UserBill.objects.get(pk=self.cleaned_data['bill_id'])
        user = User.objects.get(username=self.cleaned_data['username'])
        amount = self.cleaned_data['amount']
        if amount > bill.total_owed:
            raise Exception("Amount of $%s exceeds amount owed $%s" %(amount, bill.total_owed))
        payment = Payment.objects.create(bill=bill, user=user)
        payment.created_ts = self.cleaned_data['payment_date']
        if created_by:
            payment.created_by = User.objects.get(username=created_by)
        payment.note = self.cleaned_data['note']
        payment.amount = amount
        payment.method = self.cleaned_data['method']
        payment.save()
        return payment


class MemberSearchForm(forms.Form):
    terms = forms.CharField(max_length=100)


class NewUserForm(forms.Form):
    first_name = forms.CharField(max_length=100, label="First name *", required=True, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    last_name = forms.CharField(max_length=100, label="Last name *", required=True, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    email = forms.EmailField(max_length=100, label="Email *", required=True)

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip().title()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip().title()

    def clean_email(self):
        email = self.cleaned_data['email'].strip().lower()
        if User.objects.filter(email=email).count() > 0:
            raise forms.ValidationError("Email address '%s' already in use." % email)
        if not mailgun.MailgunAPI().validate_address(email):

nadine-2.2.3/staff/views/core.py
import os
import traceback
import operator

from datetime import date, datetime, timedelta

from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.sites.models import Site
from django.contrib import messages
from django.conf import settings

from nadine.forms import EventForm


@staff_member_required
# TODO - evaluate
def create_event(request):
    if request.method == 'POST':
        event_form = EventForm(request.POST)
        if event_form.is_valid():
            event_form.save()
            return HttpResponseRedirect(reverse('staff:tasks'))
    else:
        event_form = EventForm()
    return render(request, 'staff/create_event.html', {'event_form': event_form})


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

staff/templates/staff/settings/base.html
{% extends "staff/base.html" %}
{% load static %}

{% block sub-title %}Settings{% endblock %}

{% block pagestyle %}
  <link rel='stylesheet' href="{% static 'staff/css/settings.css' %}" />
{% endblock %}

staff/templates/staff/settings/doc_preview.html
{% load static %}
<html>
<head>
	<style>
    body {
      padding-bottom: 5%;
    }

    div {
      width: 65%;
    }

		.signature_box th {
			width: 50px;
			vertical-align: bottom;
		}

		.signature_box td {
			border-bottom: 1px solid #ccc;
			padding-bottom: 7%;
			width: 400px;
			vertical-align: bottom;
		}
	</style>
</head>
<body>
	<div id="page1_content">
		<img src="/media/documents/{{doc_type}}1.png" width='100%'/>
	</div>
	<pdf:nextpage>
	<div id="page2_content">
		<img src="/media/documents/{{doc_type}}2.png" width='100%' />
		<div class="signature_box">
			<table>
				<tr>
					<th></th>
					<th>Name:</th>
					<td></td>
				</tr>
				<tr>
					<th></th>
					<th>Date:</th>
					<td></td>
				</tr>
				<tr>
					<th></th>
					<th>Signature:</th>
					<td></td>
				</tr>
			</table>
		</div>
	</div>
</body>
</html>

staff/templates/staff/settings/doc_upload.html
{% extends "staff/settings/base.html" %}

{% block sub-title %}Document Upload {% endblock %}

{% block content %}
<h4>Document Preview and Upload</h4>
<form action='.' method='POST'>
<div style='width:50%; margin-top:2%;'>
  <h5>Preview Document</h5>
    <select name='doc_type' style='margin-top: 2%;'>
      <option selected></option>
      {% for doc in docs %}
        <option>{{ doc }}</option>
      {% endfor %}
    </select>
    <button type='submit' style='margin-top: 2%;' class='btn preview-btn'>Preview</button>
    {% csrf_token %}
</div>
</form>
<form enctype="multipart/form-data"  action='.' method='POST'>
<h5>Upload New Document</h5>
  <table>
    <tr>
      <td>
        <strong>Document Name</strong>
      </td>
      <td>
        {{ doc_form.name }}
      </td>
      <td>
        <strong>Select Document</strong>
      </td>
      <td>
        {{ doc_form.document }}
      </td>
    </tr>
  </table>
  <!-- <button class='preview-btn' onclick='preview()' value='preview'>Preview</button> -->
  <input class='btn doc-btn' type='submit' value='Submit'  />
  {% csrf_token %}
</form>
{% endblock %}

{% block extrajs %}
<script>
  $(document).ready(function() {
    $('.button-collapse').sideNav();
		$('.collapsible').collapsible();

    {% for message in messages %}
      {% if message.tags == 'error' %}
        Materialize.toast('{{ message }}', 60000, 'error-msg msg');
      {% else %}
        Materialize.toast('{{ message }}', 3000, '{{ message.tags }}-msg msg');
      {% endif %}
    {% endfor %}

    $(document).on('click', '#toast-container .toast', function() {
      $(this).fadeOut(function(){
        $(this).remove();
      });
    });
  })
</script>
{% endblock %}

staff/templates/staff/settings/helptexts.html
{% extends "staff/settings/base.html" %}

{% block content %}
<h4>Add or Update Help Texts</h4>
{% if message %}
  <div class='error'>
    {{ message }}
  </div>
{% endif %}
<div class='other-helps'>
  <table>
    <tr>
      <td class='motd-update'>
        <strong>To Update an Existing Help Text:</strong>
      </td>
      <td>
        <form class='text-selection' method='GET' action='.'>
          <select id='help-input' name='selected_help'>
              <option value='Select One' selected disabled="True">To Update, Select One Here</option>
            {% for help in helps %}
              <option value='{{ help.title }}'>{{ help.title }}</option>
            {% endfor %}
          </select>
          <input style='display: inline-block;' class='btn' type='submit' value='Start Updating' />
        </form>
      </td>
    </tr>
  </table>
</div>
<table class='alt-message'>
  <tr>
    <td class='border-td'><hr /></td>
    <td><strong id='new-message-td'>Or Create a Help Text</strong></td>
    <td class='border-td'><hr /></td>
  </tr>
</table>
<div class='helptext-form'>
  <form method='POST' action='.'>
    <table>
      <tr class='order-row'>
        <td class='td-title'></td>
        <td>
          {{ helptext_form.order }}
        </td>
      </tr>
      <tr>
        <td class='td-title'><strong>Title</strong></td>
        <td>
          {{ helptext_form.title}}
        </td>
      </tr>
    </table>
    <table id='template_help'>
      <tr>
        <td>
          <strong>Template Help</strong>
          <p>
            This is the meat of your help text! With this editor you can style the information just as you would in any editing application. Bold, special characters, tables, etc all work in this editor. Two things to note:
          </p>
          <ul>
            <li>
              - All Nadine links entered have to follow the style with "url path:to:page" sandwiched between a set of curly braces and percentage signs "{%".
            </li>
            <li>
              - The title of the text will appear as a Heading 1 (h1) so please make sure that all text is Heading 2 and smaller.
            </li>
          </ul>
        </td>
      </tr>
    </table>
    <table>
      <tr>
        <td class='td-title'><strong>Template</strong> (<a onclick="$('#template_help').toggle();">?</a>)</td>
          <input name='id' id='text-id' type='hidden' value='{{ selected.id }}' />
          <td>
            {% if selected %}
              <textarea name='template' id='id_template' rows='20'>
                {{ selected.template|safe }}
              </textarea>
            {% else %}
                {{ helptext_form.template }}
            {% endif %}
          </td>
      </tr>
    </table>
    <table id='slug_help'>
      <tr>
        <td>
          <strong>What is a 'slug'?</strong>
          <p>
            The slug is the exact address for the help text post. In this case, you'll be able to find your help text at /member/help/YOUR_SLUG/. Make sure to not include any whitespaces.
          </p>
        </td>
      </tr>
    </table>
    <table>
      <tr>
        <td class='td-title'><strong>URL Slug</strong>(<a onclick="$('#slug_help').toggle();">?</a>)</td>
        <td>
          {{ helptext_form.slug }}
        </td>
      </tr>
    </table>
    {% csrf_token %}
    {% if selected %}
      <button style='display:inline-block;' type='submit' class='btn help-btn'>Update '{{ selected.title }}'</button>
      <span id='cancel' class='help-btn'>Cancel</span>
    {% else %}
      <button type='submit' class='btn help-btn'>Add New Help Text</button>
    {% endif %}
  </form>
</div>
<script>
  $(document).ready(function() {
    $('.button-collapse').sideNav();
    $('.collapsible').collapsible();
    $('#id_order').val('{{ latest_order }}');
    $('input').attr('required', true);

    CKEDITOR.replace('id_template');

    if('{{ selected }}' != 'None') {
      $('#new-message-td').text('Start Updating!')
      //How can we have them update the template? Currently getting an error
      $('#id_title').val('{{ selected.title }}');
      $('#help-input').val('{{ selected.title }}')
      $('#id_slug').val('{{ selected.slug }}');
      $('#id_order').val('{{ selected.order}}');
    }

    $('#cancel').on('click', function(e) {
      e.preventDefault();
      window.location.replace("{% url 'staff:settings:helptexts' %}");
    })
  });
</script>
{% endblock %}

staff/templates/staff/settings/motd.html
{% extends "staff/settings/base.html" %}

{% block content %}
  <h4>Add or Update a Message of the Day</h4>
  {% if message %}
    <div class='error'>
      {{ message }}
    </div>
  {% endif %}
  <br />
  <div class='previous-motds'>
    <table>
      <tr>
        <td class='motd-update'>
          <strong>To Update an Existing Message of the Day:</strong>
        </td>
        <td>
          <form class='text-selection' method='GET' action='.'>
            <select id='motd-input' name='selected_motd'>
                <option value='Select One' selected disabled="True"> Select A Time Period Here</option>
              {% for motd in prev_motd %}
                <option value='{{ motd.id }}'>{{ motd.start_ts|date:'D M d, Y' }} - {{ motd.end_ts|date:'D M d, Y' }}</option>
              {% endfor %}
            </select>
            <input style='display: inline-block;' class='btn motd-btn' type='submit' value='Start Updating' />
          </form>
        </td>
      </tr>
    </table>
  </div>
  <table class='alt-message'>
    <tr>
      <td class='border-td'><hr /></td>
      <td><strong id='new-message-td'>Or Enter New Message</strong></td>
      <td class='border-td'><hr /></td>
    </tr>
  </table>
  <form method='POST' action='.'>
    <table>
      <tr class='motd-date-row'>
        <td class='motd-dates'>
          <strong>Starting:</strong> {{ motd_form.start_ts }}
          {% if selected %}{% else %}
          <input id='single_day' type='checkbox' name='single_day' />
          <label for='single_day'>Just One Day</label>
          {% endif %}
        </td>
        <td class='motd-dates end-td'>
          <strong>Ending:</strong> {{ motd_form.end_ts }}
        </td>
      </tr>
    </table>
    <div class='template-div'>
      <input name='id' id='text-id' type='hidden' value='{{ selected.id }}' />
      {% if selected %}
        <textarea name='message' id='id_message' rows='20'>
          {{ selected.message|safe }}
        </textarea>
      {% else %}
        <textarea name='message' id='id_message' rows='20'>
        </textarea>
      {% endif %}
    </div>
    {{ motd_form.delay_ms }}
    <br />
    {% if selected %}
      <input type='submit' class='btn' style='margin-left: 15%;' value='Update Message for {{ selected.start_ts|date:"m-d-Y" }} to {{ selected.end_ts|date:"m-d-Y" }}' />
      <span id='cancel' class='help-btn'>Cancel</span>
    {% else %}
      <input type='submit' class='btn' value='Post New Message' style='margin-left: 25%;'/>
      <span id='cancel' class='help-btn'>Cancel</span>
    {% endif %}
    {% csrf_token %}
  </form>
{% endblock %}

{% block extrajs %}
  <script>
    $(document).ready(function() {
      $('.button-collapse').sideNav();
      $('.collapsible').collapsible();
      CKEDITOR.replace('id_message');
      $('#id_start_ts').addClass('datepicker');
      $('#id_end_ts').addClass('datepicker');
      $('#id_start_ts').val(formatDate(new Date()));

      $('#id_delay_ms').val('{{ delay }}');
      $('#id_start_ts').attr('required', true);
      $('#id_message').attr('required', true);

      $('.datepicker').datepicker({
        dateFormat: 'yy-mm-dd',
        minDate: 0
      })

      $('#single_day').click(function() {
        $('.end-td').toggle();
        var date = new Date($('#id_start_ts').datepicker('getDate'));
        date.setDate(date.getDate() + 1);
        var final = formatDate(date);
        $('#id_end_ts').val(final);
      });

      if('{{ selected.id }}') {
        $('#motd-input').val("{{ selected.id }}");
        $('#new-message-td').text('Update Text');
        $('#id_start_ts').val("{{ selected.start_ts|date:'Y-m-d' }}");
        $('#id_end_ts').val("{{ selected.end_ts|date:'Y-m-d' }}");
        $('#id_messge').val('{{ selected.message }}');

        //Disabling datepicker when updating a MOTD
        $('#id_start_ts').attr('readonly', 'true');
        $('#id_end_ts').attr('readonly', 'true')
        $('#id_start_ts').removeClass('datepicker').removeClass('hasDatepicker');
        $('#id_end_ts').removeClass('datepicker').removeClass('hasDatepicker');
      } else {
        $('#id_start_ts').addClass('datepicker');
        $('#id_end_ts').addClass('datepicker');
      }

      $('#cancel').on('click', function(e) {
        e.preventDefault();
        window.location.replace("{% url 'staff:settings:motd' %}");
      })

      function formatDate(d) {
        var month = '' + (d.getMonth() + 1);
        var day = '' + d.getDate();
        var year = d.getFullYear();

        if (month.length < 2) {
          month = '0' + month;
        }
        if (day.length < 2) {
          day = '0' + day;
        }

        return [year, month, day].join('-');
      }
    });
  </script>
{% endblock %}

staff/templates/staff/settings/nav.html
<li>
  <a href="{% url 'staff:settings:index' %}">General Settings</a>
</li>
<li>
  <a href="{% url 'staff:settings:helptexts' %}">Help Texts</a>
</li>
<li>
  <a href="{% url 'staff:settings:motd' %}">MOTD</a>
</li>
<li>
  <a href="{% url 'staff:settings:membership_packages' %}">Membership Packages</a>
</li>
<li>
  <a href="{% url 'staff:settings:edit_rooms' %}">Edit Rooms</a>
</li>