nadine-2.2.3/tablet/urls.py
from django.shortcuts import redirect
from django.urls import include, path

from . import views

app_name = 'tablet'
urlpatterns = [
    path('', lambda r: redirect('tablet:motd'), name="home"),
    path('members/', views.members, name='members'),
    path('motd/', views.motd, name='motd'),
    path('here_today/', views.here_today, name='here_today'),
    path('visitors/', views.visitors, name='visitors'),
    path('search/', views.search, name='search'),
    path('welcome/<username>/', views.welcome, name='welcome'),
    path('profile/<username>/', views.user_profile, name='user_profile'),
    path('post_create/<username>/', views.post_create, name='post_create'),
    path('<username>/signin/', views.signin_user, name='signin_user'),
    path('<username>/guestof/<paid_by>/', views.signin_user_guest, name='signin_guest'),
    path('<username>/documents/', views.document_list, name='document_list'),
    path('<username>/document/<doc_type>/', views.document_view, name='document_view'),
    path('<username>/signature/<doc_type>/', views.signature_capture, name='sig_capture'),
    path('<username>/signature/<doc_type>/<signature_file>', views.signature_render, name='sig_render'),
]

# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

tablet/urls.py
from django.shortcuts import redirect
from django.urls import include, path

from . import views

app_name = 'tablet'
urlpatterns = [
    path('', lambda r: redirect('tablet:motd'), name="home"),
    path('members/', views.members, name='members'),
    path('motd/', views.motd, name='motd'),
    path('here_today/', views.here_today, name='here_today'),
    path('visitors/', views.visitors, name='visitors'),
    path('search/', views.search, name='search'),
    path('welcome/<username>/', views.welcome, name='welcome'),
    path('profile/<username>/', views.user_profile, name='user_profile'),
    path('post_create/<username>/', views.post_create, name='post_create'),
    path('<username>/signin/', views.signin_user, name='signin_user'),
    path('<username>/guestof/<paid_by>/', views.signin_user_guest, name='signin_guest'),
    path('<username>/documents/', views.document_list, name='document_list'),
    path('<username>/document/<doc_type>/', views.document_view, name='document_view'),
    path('<username>/signature/<doc_type>/', views.signature_capture, name='sig_capture'),
    path('<username>/signature/<doc_type>/<signature_file>', views.signature_render, name='sig_render'),
]

# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

urls.py
import time

from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

import views


admin.autodiscover()

app_name = 'nadine'
urlpatterns = [
    path('', views.index, name='site_index'),
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    path('robots.txt', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    path('cache.manifest', lambda r: HttpResponse(get_manifest(), content_type="text/plain")),

    path('account/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),

    path('staff/', include('staff.urls', namespace='staff')),
    path('member/', include('member.urls', namespace='member')),
    path('tablet/', include('tablet.urls', namespace='tablet')),
    path('doors/', include('doors.keymaster.urls', namespace='doors')),
    path('logs/', include('arpwatch.urls', namespace='arp')),
    path('comlink/', include('comlink.urls', namespace='comlink')),

    path('email/add/', views.email_add, name='email_add'),
    path('email/manage/<email_pk>/<action>/', views.email_manage, name='email_manage'),
    path('email/verify/<email_pk>/', views.email_verify, name='email_verify'),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


def get_manifest():
    return "CACHE MANIFEST\n#Time: %s\nCACHE:\nFALLBACK:\nNETWORK:\n*" % time.time()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine/forms.py
import logging
import datetime
import base64
import uuid
import os
from datetime import datetime, timedelta

from django import forms
from django.core.files.base import ContentFile
from django.forms import modelformset_factory
from django.forms.formsets import BaseFormSet
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.base import ContentFile
from django.utils.timezone import localtime, now
from django.shortcuts import get_object_or_404

from localflavor.us.us_states import US_STATES
from localflavor.ca.ca_provinces import PROVINCE_CHOICES

from comlink import mailgun

from nadine.models.core import HowHeard, Industry, Neighborhood, URLType, GENDER_CHOICES
from nadine.models.profile import UserProfile, MemberNote, user_photo_path
from nadine.models.membership import Membership, MembershipPackage, ResourceSubscription, IndividualMembership, SubscriptionDefault
from nadine.models.usage import PAYMENT_CHOICES, CoworkingDay
from nadine.models.resource import Room, Resource
from nadine.models.organization import Organization, OrganizationMember
from nadine.models.billing import UserBill, Payment, PaymentMethod
from nadine.utils.payment_api import PaymentAPI
from member.models import HelpText, MOTD

logger = logging.getLogger(__name__)


class DateRangeForm(forms.Form):
    START_DATE_PARAM = 'start'
    END_DATE_PARAM = 'end'

    start = forms.DateField()
    end = forms.DateField()

    @staticmethod
    def from_request(request, days=31):
        # Pull the start and end parameters
        start_param = DateRangeForm.START_DATE_PARAM
        end_param = DateRangeForm.END_DATE_PARAM
        # Get our start date
        start_str = request.POST.get(start_param, None)
        if not start_str:
            start_str = request.GET.get(start_param, None)
        if not start_str:
            start_date = localtime(now()).date() - timedelta(days=days)
            start_str = start_date.isoformat()
        # Get our end date
        end_str = request.POST.get(end_param, None)
        if not end_str:
            end_str = request.GET.get(end_param, None)
        if not end_str:
            tomorrow = localtime(now()) + timedelta(days=1)
            end_str = tomorrow.date().isoformat()
        return DateRangeForm({start_param: start_str, end_param: end_str})

    def get_dates(self):
        if not self.is_valid():
            return (None, None)
        return (self.cleaned_data['start'], self.cleaned_data['end'])


class OrganizationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            self.instance = kwargs['instance']
            del kwargs['instance']
        super(OrganizationForm, self).__init__(*args, **kwargs)
        if hasattr(self, 'instance'):
            self.initial['org_id'] = self.instance.id
            self.initial['name'] = self.instance.name
            self.initial['blurb'] = self.instance.blurb
            self.initial['bio'] = self.instance.bio
            self.initial['photo'] = self.instance.photo
            self.initial['public'] = self.instance.public
            #self.initial['locked'] = self.instance.locked

    org_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    name = forms.CharField(min_length=1, max_length=128, label="Organization Name", required=True, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    blurb = forms.CharField(widget=forms.Textarea, max_length=112, required=False)
    bio = forms.CharField(widget=forms.Textarea, max_length=512, required=False)
    photo = forms.FileField(required=False)
    public = forms.BooleanField(required=False)
    #locked = forms.BooleanField(required=False)

    def save(self):
        org_id = self.cleaned_data['org_id']
        org = Organization.objects.get(id=org_id)
        org.name = self.cleaned_data['name']
        org.blurb = self.cleaned_data['blurb']
        org.bio = self.cleaned_data['bio']
        if self.cleaned_data['photo']:
            # Delete the old one before we save the new one
            org.photo.delete()
            org.photo = self.cleaned_data['photo']
        if 'public' in self.cleaned_data:
            org.public = self.cleaned_data['public']
        if 'locked' in self.cleaned_data:
            org.locked = self.cleaned_data['locked']
        org.save()


class OrganizationSearchForm(forms.Form):
    terms = forms.CharField(max_length=100)


class OrganizationMemberForm(forms.Form):
    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            self.instance = kwargs['instance']
            del kwargs['instance']
        super(OrganizationMemberForm, self).__init__(*args, **kwargs)
        if hasattr(self, 'instance'):
            self.initial['member_id'] = self.instance.id
            self.initial['org_id'] = self.instance.organization.id
            self.initial['username'] = self.instance.user.username
            self.initial['title'] = self.instance.title
            self.initial['start_date'] = self.instance.start_date
            self.initial['end_date'] = self.instance.end_date
            self.initial['admin'] = self.instance.admin

    org_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    member_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    username = forms.CharField(required=False, widget=forms.HiddenInput)
    title = forms.CharField(max_length=128, required=False, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder':'e.g. 12/28/16', 'class':'datepicker'}, format='%m/%d/%Y'), required=True)
    end_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder':'e.g. 12/28/16', 'class':'datepicker'}, format='%m/%d/%Y'), required=False)
    admin = forms.BooleanField(required=False)

    def is_valid(self):
        # run the parent validation first
        super_valid = super(OrganizationMemberForm, self).is_valid()
        has_member_id = 'member_id' in self.cleaned_data and self.cleaned_data['member_id']
        has_username = 'username' in self.cleaned_data and self.cleaned_data['username']
        if not (has_member_id or has_username):
            self.add_error('username', 'No user data provided')
        return super_valid and (has_member_id or has_username)

    def clean_member(self):
        self.member = None
        self.organization = Organization.objects.get(id=self.cleaned_data['org_id'])

        # Populate our member from either member_id (edit) or username (add)
        member_id = self.cleaned_data['member_id']
        username=self.cleaned_data['username']
        if member_id:
            self.member = OrganizationMember.objects.get(id=member_id)
        elif username:
            user = User.objects.get(username=username)
            self.member = OrganizationMember(organization=self.organization, user=user)
        else:
            raise Exception("Form must contain member_id or username!")

        return self.member

    def save(self):
        if not self.is_valid():
            raise Exception('The form must be valid in order to save')
        member = self.clean_member()
        member.title = self.cleaned_data['title']
        member.start_date = self.cleaned_data['start_date']
        member.end_date = self.cleaned_data['end_date']
        if 'admin' in self.cleaned_data:
            member.admin = self.cleaned_data['admin']
        member.save()


class PaymentForm(forms.Form):
    bill_id = forms.IntegerField(required=True, widget=forms.HiddenInput)
    username = forms.CharField(required=True, widget=forms.HiddenInput)
    # created_by = forms.CharField(required=False, widget=forms.HiddenInput)
    payment_date = forms.DateField(required=True, widget=forms.DateInput(attrs={'placeholder':'e.g. 12/28/16', 'class':'datepicker'}, format='%m/%d/%Y'))
    method = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'browser-default'}), label="Payment method", queryset=PaymentMethod.objects.all(), required=False)
    note = forms.CharField(max_length=256, required=False)
    amount = forms.DecimalField(min_value=0, max_value=10000, required=True, max_digits=7, decimal_places=2)

    def save(self, created_by=None):
        bill = UserBill.objects.get(pk=self.cleaned_data['bill_id'])
        user = User.objects.get(username=self.cleaned_data['username'])
        amount = self.cleaned_data['amount']
        if amount > bill.total_owed:
            raise Exception("Amount of $%s exceeds amount owed $%s" %(amount, bill.total_owed))
        payment = Payment.objects.create(bill=bill, user=user)
        payment.created_ts = self.cleaned_data['payment_date']
        if created_by:
            payment.created_by = User.objects.get(username=created_by)
        payment.note = self.cleaned_data['note']
        payment.amount = amount
        payment.method = self.cleaned_data['method']
        payment.save()
        return payment


class MemberSearchForm(forms.Form):
    terms = forms.CharField(max_length=100)


class NewUserForm(forms.Form):
    first_name = forms.CharField(max_length=100, label="First name *", required=True, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    last_name = forms.CharField(max_length=100, label="Last name *", required=True, widget=forms.TextInput(attrs={'autocapitalize': "words"}))
    email = forms.EmailField(max_length=100, label="Email *", required=True)

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip().title()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip().title()

    def clean_email(self):
        email = self.cleaned_data['email'].strip().lower()
        if User.objects.filter(email=email).count() > 0:
            raise forms.ValidationError("Email address '%s' already in use." % email)
        if not mailgun.MailgunAPI().validate_address(email):

tablet/forms.py
import os
import uuid
import base64
from io import StringIO

from jsignature.forms import JSignatureField
from jsignature.utils import draw_signature

from django import forms
from django.conf import settings


class SignatureForm(forms.Form):
    signature = JSignatureField()
    file_name = None

    def has_signature(self):
        return self.is_valid() and self.cleaned_data.get('signature')

    def signature_file(self):
        if not self.file_name:
            self.file_name = "%s.png" % uuid.uuid4()
        return self.file_name

    def signature_path(self):
        return os.path.join(settings.MEDIA_ROOT, "signatures/%s" % self.signature_file())

    def raw_signature_data(self):
        signature_picture = draw_signature(self.cleaned_data.get('signature'))
        output = StringIO.StringIO()
        signature_picture.save(output, format="PNG")
        contents = output.getvalue()
        output.close()
        image_data = base64.b64encode(contents)
        return image_data

    def save_signature(self):
        signature_picture = draw_signature(self.cleaned_data.get('signature'))
        signature_picture.save(self.signature_path())
        return self.signature_file()


# Copyright 2020 Office Nomads LLC (https://officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://opensource.org/licenses/Apache-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

nadine-2.2.3/tablet/templates/tablet/document_list.html
{% extends "tablet/t_base.html" %}
{% load static %}

{% block nav-members %} class="ui-btn-active" {% endblock %}

{% block content %}
	<h2>Documents for {{ user.get_full_name }}</h2>
	<div style="margin-left: 3em;">
	<table style="border: 1px solid black;">
		<tr>
			<th></th>
			<th>Document</th>
			<th>Date</th>
			<th></th>
		</tr>
	{% for doc in documents %}
		<tr>
			<td style="vertical-align:middle; text-align:center;">
				{% if doc.file %}
					<img src="{% static 'green_check.png' %}" height="32px">
				{% endif %}
			</td>

			<td style="vertical-align:middle;">
				{% if doc.file %}
					<a href="{% get_media_prefix %}{{ doc.file.file.name }}">{{ doc.description }}</a>
				{% else %}
					{{ doc.description }}
				{% endif %}
			</td>

			<td style="vertical-align:middle;">{{ doc.file.uploadTS|date:"M d, Y" }}</td>
			<th>
					<input type="button"
						value="Sign"
						onClick="parent.location='{% url 'tablet:sig_capture' user.username doc.key %}'" />
			</th>
		</tr>
	{% endfor %}
	</table>
	</div>
{% endblock %}

nadine-2.2.3/tablet/templates/tablet/members.html
{% extends "tablet/t_base.html" %}
{% load imagetags %}

{% block nav-members %} class="ui-btn-active" {% endblock %}

{% block content %}
	{% if list_members %}
		{% if members %}
			<ul data-role="listview" data-inset="true">
				{% for u in members %}
					<li >
						<a href="{% url 'tablet:user_profile' u.username %}" data-transition="fade" style="font-size: 1.3em;">{{ u.get_full_name }}</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<h2>No Members</h2>
		{% endif %}
		<input type="button" data-theme="E" onclick="window.location='{% url 'tablet:members' %}'" value="Back"/>
	{% else %}
		<h2>What is the first letter of your <em><u>first name</u></em>?</h2>
		<div id="tiles">
			<span class="tile"><a href="?startswith=A">A</a></span>
			<span class="tile"><a href="?startswith=B">B</a></span>
			<span class="tile"><a href="?startswith=C">C</a></span>
			<span class="tile"><a href="?startswith=D">D</a></span>
			<span class="tile"><a href="?startswith=E">E</a></span>
			<span class="tile"><a href="?startswith=F">F</a></span>
			<span class="tile"><a href="?startswith=G">G</a></span>
			<span class="tile"><a href="?startswith=H">H</a></span>
			<span class="tile"><a href="?startswith=I">I</a></span>
			<span class="tile"><a href="?startswith=J">J</a></span>
			<span class="tile"><a href="?startswith=K">K</a></span>
			<span class="tile"><a href="?startswith=L">L</a></span>
			<span class="tile"><a href="?startswith=M">M</a></span>
			<span class="tile"><a href="?startswith=N">N</a></span>
			<span class="tile"><a href="?startswith=O">O</a></span>
			<span class="tile"><a href="?startswith=P">P</a></span>
			<span class="tile"><a href="?startswith=Q">Q</a></span>
			<span class="tile"><a href="?startswith=R">R</a></span>
			<span class="tile"><a href="?startswith=S">S</a></span>
			<span class="tile"><a href="?startswith=T">T</a></span>
			<span class="tile"><a href="?startswith=U">U</a></span>
			<span class="tile"><a href="?startswith=V">V</a></span>
			<span class="tile"><a href="?startswith=W">W</a></span>
			<span class="tile"><a href="?startswith=X">X</a></span>
			<span class="tile"><a href="?startswith=Y">Y</a></span>
			<span class="tile"><a href="?startswith=Z">Z</a></span>
			<span class="tile"><a href="{% url 'tablet:search' %}">?</a></span>
		</div>
		<button style='width: 20%; margin-left:40%; margin-top: 10%; background-color: RGBA(51, 136, 204, 1.00); color: white; text-shadow: none; padding: 1%;font-size: .8em; border-radius: 3px;' class='btn' onClick="location.href='{% url 'tablet:motd' %}'">Home</button>
	{% endif %}
{% endblock %}

nadine-2.2.3/tablet/templates/tablet/post_create.html
{% extends "tablet/t_base.html" %}
{% load imagetags %}

{% block nav-visitors %} class="ui-btn-active" {% endblock %}

{% block style %}
	#yes_button {
		background:#1BA512;
		color:white;
		opacity:.5;
	}
	#no_button {
		background:#DB0303;
		color:white;
		opacity:.5;
	}
	#guest_button {
		background:#0B79D0;
		color:white;
		opacity:.5;
	}
{% endblock %}

{% block content %}
	<div style="font-size: 150%;">Welcome to Office Nomads!</div>

	<p>
	We have created a new user in Nadine. You can use Nadine to enter billing information, review your membership, your daily activity, and explore everything
	that is going on here at Office Nomads.
	</p>
	<p style="padding-left:3em;">
		Enjoy!<br>
		-- The Office Nomads Team
	</p>

	<h2>User Information</h2>
	<blockquote>
		<p>Username: <strong>{{ user.username }}</strong>
		<p>Full Name: <strong>{{ user.get_full_name }}</strong>
		<p>Email: <strong>{{ user.email }}</em></strong>
	</blockquote>

	<div id="guestform-show"></div>

	<div style="width:100%; text-align:center;" id="signin" {% if search_results %} class="hidden" {% endif %}>
	<h2>Are you going to stay and work today?</h2>
	<form action="{% url 'tablet:post_create' user.username %}" method="POST" data-ajax="false">
		<fieldset class="visitor-form ui-grid-b">
			<div class="ui-block-a"><input id="yes_button" name="work_today" type="Submit" value="Yes"/></div>
			<div class="ui-block-b"><input id="no_button" name="work_today" type="Submit" value="No"/></div>
		</fieldset>
		{% csrf_token %}
	</form>
	</div>

	<div style="width:100%; text-align:center;" id="guestform" {% if not search_results %} class="hidden" {% endif %} >
		<h2>Which member is paying for you today?</h2>
		{% if search_results %}
			<div id="member-list">
				<ul data-role="listview" data-inset="true" data-filter="false">
					{% for u in search_results %}
						<li style="padding: 0.5em;"><a href="{% url 'tablet:signin_guest' user.username u.username %}" data-transition="fade">{{ u.get_full_name }}</a></li>
					{% endfor %}
				</ul>
			</div>
		{% else %}
			<div id="search-box">
				<form id="member-search-form" action="{% url 'tablet:post_create' user.username %}" method="POST">
					<input id="id_terms"  placeholder="Search by first name" type="search" name="terms" maxlength="100"/>
					<input type="submit" value="Search" data-theme="b" data-transition="fade"/>
					{% csrf_token %}
				</form>
			</div>
		{% endif %}
	</div>
{% endblock %}

nadine-2.2.3/tablet/templates/tablet/search.html
{% extends "tablet/t_base.html" %}
{% load imagetags %}

{% block nav-members %} class="ui-btn-active" {% endblock %}

{% block content %}
	{% if search_results %}
		<h2>Search Results</h2>
		<div id="member-list">
			<ul data-role="listview" data-inset="true" data-filter="false">
				{% for u in search_results %}
					<li><a href="{% url 'tablet:user_profile' u.username %}" data-transition="fade">{{ u.get_full_name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	{% else %}
		<h2>Search</h2>
		<div id="search-box">
			<form id="member-search-form" action="{% url 'tablet:search' %}" method="POST">
				<div data-role="fieldcontain">
					<input id="id_terms" type="search" maxlength="100" name="terms" type="text" />
					<input type="submit" value="Search" data-theme="b" data-transition="fade"/>
				</div>
				{% csrf_token %}
			</form>
		</div>
	{% endif %}



{% endblock %}

nadine-2.2.3/tablet/templates/tablet/user_profile.html
{% extends "tablet/t_base.html" %}
{% load imagetags %}
{% load static %}

{% block nav-members %} class="ui-btn-active" {% endblock %}

{% block content %}
	<div class="ui-grid-a">
		<div class="ui-block-a">
			{% if user.profile.photo %}
				<a href="{% url 'tablet:user_profile' user %}"><img src="{{ user.profile.photo.url }}" width="300px"></a>
			{% else %}
				<img src="{% static 'BlankIcon150x150.jpg' %}">
			{% endif %}
		</div>
		<div class="ui-block-b">
			<h2>{{ user.get_full_name }}</h2>

			{% if not user.profile.has_valid_billing %}
				<h3 style="color:red;">Please update your billing profile.</h3>
			{% endif %}

			{% if open_alerts %}
				<h4 style="color:red;">Check with {{ site.name }} staff about these required actions:</h4>
				<ul>
					{% for a in open_alerts %}
						<li style='color: red;'> {{ a.description }}</li>
					{% endfor %}
				</ul>
			{% endif %}

		{% if user.membership.active_subscriptions %}
		<h3>Billing Day: <span style="font-weight:normal;">{{ user.membership.bill_day_str }}</span></h3>

			<h3>Visits This Period:
				<span style="font-weight:normal;">{{ billable }}
					{% if day_allowance %}
						of {{ day_allowance }}
					{% endif %}
				</span>
			</h3>
			{% endif %}

			<h3><a href="{% url 'tablet:document_list' user.username %}">Sign Documents</a></h3>

			{% if can_signin and not search_results %}
				<div id="guestform-links">
					<a href="#" data-role="button" data-inline="true" data-mini="true" id="guestform-show" class="showLink" onclick="showGuestForm();return false;">Guest of another member?</a>
					<!--
					<a href="#" data-role="button" data-inline="true" data-mini="true" id="guestform-hide" class="hideLink" onclick="hideGuestForm();return false;">Cancel Guest Sign-in.</a>-->
				</div>
			{% endif %}
		</div>
	</div>

	{% if can_signin %}
		<div id="guestform" {% if not search_results %} class="hidden" {% endif %} >
			<h3>Which member is paying for you today?</h3>
			{% if previous_hosts %}
				<div id="member-list">
					<ul data-role="listview" data-inset="true" data-filter="false">
						{% for u in previous_hosts %}
							<li style="padding: 0.5em;"><a href="{% url 'tablet:signin_guest' user.username u.username %}" data-transition="fade">{{ u.get_full_name }}</a></li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}

			{% if search_results %}
				<div id="member-list">
					<ul data-role="listview" data-inset="true" data-filter="false">
						{% for u in search_results %}
							<li style="padding: 0.5em;"><a href="{% url 'tablet:signin_guest' user.username u.username %}" data-transition="fade">{{ u.get_full_name }}</a></li>
						{% endfor %}
					</ul>
				</div>
			{% else %}
				<div id="search-box">
					<form id="member-search-form" action="{% url 'tablet:user_profile' user.username %}" method="POST">
						<input id="id_terms"  placeholder="Search by first name" type="search" name="terms" maxlength="100"/>
						<input type="submit" value="Search" data-theme="b" data-transition="fade"/>
						{% csrf_token %}
					</form>
				</div>
			{% endif %}
		</div>

		<div id="signin" data-theme="a" {% if search_results %} class="hidden" {% endif %}>
			<a href="{% url 'tablet:signin_user' user.username %}" data-role="button" data-theme="b" data-transition="fade">Sign In</a>
		</div>
	{% endif %}
{% endblock %}